var cts3_questions = {
    "questions": [
        {
            "id": "cts3_1",
            "question": "When checking signal flow, the first thing you need to confirm is that the signal is",
            "options": [
                "being generated by the source components"
            ],
            "answer": "being generated by the source components"
        },
        {
            "id": "cts3_2",
            "question": "There are eight loudspeakers wired in parallel and each loudspeaker's impedance is 16 ohms. The impedance of the circuit is _____ ohms.",
            "options": [
                "2 ohms"
            ],
            "answer": "2 ohms"
        },
        {
            "id": "cts3_3",
            "question": "There are four loudspeakers wired in parallel. Two of the loudspeakers each have an impedance of 8 ohms. Two of the loudspeakers each have an impedance of 16 ohms. Calculate the impedance of this parallel circuit.",
            "options": [
                "2.7 ohms"
            ],
            "answer": "2.7 ohms"
        },
        {
            "id": "cts3_4",
            "question": "It is an industry best practice to use no less than _____ ISO rated hardware for an audio visual installation",
            "options": [
                "8.8"
            ],
            "answer": "8.8"
        },
        {
            "id": "cts3_5",
            "question": "If there are _____ bumps on the head of an ASTM ASE graded bolt, it is grade 5.",
            "options": [
                "3"
            ],
            "answer": "3"
        },
        {
            "id": "cts3_6",
            "question": "In mounting, _____ refers to the hardware's elasticity.",
            "options": [
                "tensile strength"
            ],
            "answer": "tensile strength"
        },
        {
            "id": "cts3_7",
            "question": "_____ is how likely the wall and the mounting are to be cut in two.",
            "options": [
                "Shear"
            ],
            "answer": "Shear"
        },
        {
            "id": "cts3_8",
            "question": "The following lists methods of control for an AV system.",
            "options": [
                "IR, TCP/IP, RS-232"
            ],
            "answer": "IR, TCP/IP, RS-232"
        },
        {
            "id": "cts3_9",
            "question": "The _____ interconnects the various pieces of a control system and provides the power for them operate and the communication among them.",
            "options": [
                "Control bus"
            ],
            "answer": "Control bus"
        },
        {
            "id": "cts3_10",
            "question": "Select the true statement:",
            "options": [
                "Conduits and ducts are types of raceways"
            ],
            "answer": "Conduits and ducts are types of raceways"
        },
        {
            "id": "cts3_11",
            "question": "The permissible area for one cable in a conduit is limited to _____ percent of the conduit area.",
            "options": [
                "53%"
            ],
            "answer": "53%"
        },
        {
            "id": "cts3_12",
            "question": "The permissible area for two cables in a conduit is limited to _____ percent of the conduit area.",
            "options": [
                "31%"
            ],
            "answer": "31%"
        },
        {
            "id": "cts3_13",
            "question": "The permissible area for three or more cables in a conduit is limited to _____ percent of the conduit area.",
            "options": [
                "40%"
            ],
            "answer": "40%"
        },
        {
            "id": "cts3_14",
            "question": "When stripping cable it is best to use:",
            "options": [
                "Designated strippers."
            ],
            "answer": "Designated strippers."
        },
        {
            "id": "cts3_15",
            "question": "Where can you usually find appropriate stripping dimensions for a cable?",
            "options": [
                "On the connector packaging"
            ],
            "answer": "On the connector packaging"
        },
        {
            "id": "cts3_16",
            "question": "When using a coaxial stripping tool to cleanly strip coax cable, _____ so the blades can cut through the jacket, shield and dielectric at the proper points.",
            "options": [
                "rotate the stripper around the cable several times"
            ],
            "answer": "rotate the stripper around the cable several times"
        },
        {
            "id": "cts3_17",
            "question": "120V three-phase power distribution system uses _____ wires.",
            "options": [
                "four"
            ],
            "answer": "four"
        },
        {
            "id": "cts3_18",
            "question": "When AV systems incorporate lighting controls, special considerations are given when the lighting is run on a _____ power system.",
            "options": [
                "277 V"
            ],
            "answer": "277 V"
        },
        {
            "id": "cts3_19",
            "question": "The purpose of electrical grounding is to",
            "options": [
                "ensure safety"
            ],
            "answer": "ensure safety"
        },
        {
            "id": "cts3_20",
            "question": "When conducting a complete project bid process, what milestone follows the issuing of the RFP?",
            "options": [
                "Pre-Bid Meeting"
            ],
            "answer": "Pre-Bid Meeting"
        },
        {
            "id": "cts3_21",
            "question": "When terminating a Category 5e cable with an 8P8C (RJ-45) connector, it is best practice to untwist each wire pair:",
            "options": [
                "As little as possible to get each wire to enter the proper channel in the connector"
            ],
            "answer": "As little as possible to get each wire to enter the proper channel in the connector"
        },
        {
            "id": "cts3_22",
            "question": "A camera was installed about 180' (55m) from its 1.5A 12v power supply, the power supply is dead, and needs replacing. Assuming that the camera can operate normally within +/- 10% of the power supply voltage, if 18 gauge wire was run initially and an almost 3v drop is present, what is the correct action?",
            "options": [
                "Re-locate the power supply near the camera"
            ],
            "answer": "Re-locate the power supply near the camera"
        },
        {
            "id": "cts3_23",
            "question": "There is concern about the noise level in an AV rack room. What weight setting on the SPL meter should be used to demonstrate that the noise level doesn't require hearing protection at all times?",
            "options": [
                "A Weighted"
            ],
            "answer": "A Weighted"
        },
        {
            "id": "cts3_24",
            "question": "On a new construction project, there is a need to verify that power has been installed in the correct place. Who should be contacted to verify this information?",
            "options": [
                "Project Manager"
            ],
            "answer": "Project Manager"
        },
        {
            "id": "cts3_25",
            "question": "Technical support funding can include money for training and",
            "options": [
                "Hiring additional staff"
            ],
            "answer": "Hiring additional staff"
        },
        {
            "id": "cts3_26",
            "question": "One way to efficiently manage a construction schedule is to use a",
            "options": [
                "Gantt chart"
            ],
            "answer": "Gantt chart"
        },
        {
            "id": "cts3_27",
            "question": "During the Construction Phase, what is likely to happen if a product is suddenly discontinued?",
            "options": [
                "A request for change (RFC) may be submitted"
            ],
            "answer": "A request for change (RFC) may be submitted"
        },
        {
            "id": "cts3_28",
            "question": "During shop testing, is/are checked and is/are tested.",
            "options": [
                "Proper functioning of equipment, software"
            ],
            "answer": "Proper functioning of equipment, software"
        },
        {
            "id": "cts3_29",
            "question": "Where does the initial testing of a pre-assembled AV system typically occur in the Construction Phase?",
            "options": [
                "At the warehouse, when the equipment is delivered"
            ],
            "answer": "At the warehouse, when the equipment is delivered"
        },
        {
            "id": "cts3_30",
            "question": "During the Design Phase, it is important to coordinate with which of the following trades?",
            "options": [
                "Architect, electrical consultant, construction manager"
            ],
            "answer": "Architect, electrical consultant, construction manager"
        },
        {
            "id": "cts3_31",
            "question": "The correct time to discuss visible finishes for wall plates, surface mount speakers, and wall mounted screen casings is during the:",
            "options": [
                "Site Survey"
            ],
            "answer": "Site Survey"
        },
        {
            "id": "cts3_32",
            "question": "When terminating an Ethernet cable, what connector type is normally used?",
            "options": [
                "RJ45"
            ],
            "answer": "RJ45"
        },
        {
            "id": "cts3_33",
            "question": "What must be considered during rack assembly?",
            "options": [
                "Ergonomics of equipment placement, signal separation, heat load, weight distribution."
            ],
            "answer": "Ergonomics of equipment placement, signal separation, heat load, weight distribution."
        },
        {
            "id": "cts3_34",
            "question": "If you are projecting onto a screen that is 10 feet (3 meters) wide and your projection distance to screenwidth ratio is 2.0:1, what should be the distance of the projector from the screen?",
            "options": [
                "20 feet (6 meters)"
            ],
            "answer": "20 feet (6 meters)"
        },
        {
            "id": "cts3_35",
            "question": "When checking signal flow, the FIRST thing you need to confirm is that the signal is:",
            "options": [
                "being generated by the source components."
            ],
            "answer": "being generated by the source components."
        },
        {
            "id": "cts3_36",
            "question": "At the end of an event how does one quickly and safely strike the event?",
            "options": [
                "Strike equipment by category and divide into teams."
            ],
            "answer": "Strike equipment by category and divide into teams."
        },
        {
            "id": "cts3_37",
            "question": "When creating estimates for an AV project what are the primary considerations?",
            "options": [
                "Equipment & material costs, labor costs, estimate markup."
            ],
            "answer": "Equipment & material costs, labor costs, estimate markup."
        },
        {
            "id": "cts3_38",
            "question": "When purchasing AV supplies and equipment for a client AV installation project what needs to be done?",
            "options": [
                "Identify needed equipment, tools and labor, work with vendors for prices and delivery schedule."
            ],
            "answer": "Identify needed equipment, tools and labor, work with vendors for prices and delivery schedule."
        },
        {
            "id": "cts3_39",
            "question": "How can labor timesheets and invoices from previous jobs be used to increase efficiency for future AVjob estimates?",
            "options": [
                "Analysis of past costs for labor and shipping."
            ],
            "answer": "Analysis of past costs for labor and shipping."
        },
        {
            "id": "cts3_40",
            "question": "When negotiating a contract for a job that will take a long time to complete, one should consider",
            "options": [
                "Progress, stage, or interim invoicing"
            ],
            "answer": "Progress, stage, or interim invoicing"
        },
        {
            "id": "cts3_41",
            "question": "When conducting a site visit, if a ladder is needed what type should be used?",
            "options": [
                "Fiberglass or wood."
            ],
            "answer": "Fiberglass or wood."
        },
        {
            "id": "cts3_42",
            "question": "If the displayed text size in a projection presentation is 2-inch/50-mm then the viewer should not befarther away than:",
            "options": [
                "300 inches/7,620 mm"
            ],
            "answer": "300 inches/7,620 mm"
        },
        {
            "id": "cts3_43",
            "question": "How far can RS-422 run and to how many devices",
            "options": [
                "4000 ft and up to 10 devices"
            ],
            "answer": "4000 ft and up to 10 devices"
        },
        {
            "id": "cts3_44",
            "question": "How many connectors do you need to connect an RS-232",
            "options": [
                "3 wires 2-3-5"
            ],
            "answer": "3 wires 2-3-5"
        },
        {
            "id": "cts3_45",
            "question": "If a system meets the original design, fulfills the needs of the end-user, and remains in proper working order, what will be the result?",
            "options": [
                "A successful project"
            ],
            "answer": "A successful project"
        },
        {
            "id": "cts3_46",
            "question": "What are the primary functions of Step Four of the System Commissioning and Training Phase of a project?",
            "options": [
                "Inspecting, Testing and Aligning"
            ],
            "answer": "Inspecting, Testing and Aligning"
        },
        {
            "id": "cts3_47",
            "question": "During which step in the System Commissioning and Training Phase is the final checklist for the complete installation generated?",
            "options": [
                "Generate the Punch List"
            ],
            "answer": "Generate the Punch List"
        },
        {
            "id": "cts3_48",
            "question": "Verification and Optimization are two concepts that are applied during System Commissioning to ensure that:",
            "options": [
                "The design intent has been met"
            ],
            "answer": "The design intent has been met"
        },
        {
            "id": "cts3_49",
            "question": "What is the last step of the Construction Phase",
            "options": [
                "Systems Training"
            ],
            "answer": "Systems Training"
        },
        {
            "id": "cts3_50",
            "question": "During the Construction Phase of a project, which step always follows AV System Testing?",
            "options": [
                "Site Installation"
            ],
            "answer": "Site Installation"
        },
        {
            "id": "cts3_51",
            "question": "The Owner Plays what role in the Project Lifecycle",
            "options": [
                "Buyer of the AV System"
            ],
            "answer": "Buyer of the AV System"
        },
        {
            "id": "cts3_52",
            "question": "The Generic project process contains three roles Installer, Project manager and",
            "options": [
                "Designer"
            ],
            "answer": "Designer"
        },
        {
            "id": "cts3_53",
            "question": "What stages are in both small and large construction projects",
            "options": [
                "Program, Design, Construction and Occupy"
            ],
            "answer": "Program, Design, Construction and Occupy"
        },
        {
            "id": "cts3_54",
            "question": "What type of project is suitable for a Consultant led design build",
            "options": [
                "6 months or less"
            ],
            "answer": "6 months or less"
        },
        {
            "id": "cts3_55",
            "question": "What type of project is suitable for an integrator Led Design build",
            "options": [
                "Three months or less"
            ],
            "answer": "Three months or less"
        },
        {
            "id": "cts3_56",
            "question": "What is the disadvantages of splitting the AV Equipment Contract and Labor contract",
            "options": [
                "Determining which party is responsible for AV system problems"
            ],
            "answer": "Determining which party is responsible for AV system problems"
        },
        {
            "id": "cts3_57",
            "question": "In the building process what is the first milestone",
            "options": [
                "Issue request for proposal"
            ],
            "answer": "Issue request for proposal"
        },
        {
            "id": "cts3_58",
            "question": "After witting the program report what is the next step in the program phase",
            "options": [
                "Distribute the report"
            ],
            "answer": "Distribute the report"
        },
        {
            "id": "cts3_59",
            "question": "During the System Commissioning and training phase, what is the role of the punch or checklist",
            "options": [
                "It defines the items that require resolution for project completion"
            ],
            "answer": "It defines the items that require resolution for project completion"
        },
        {
            "id": "cts3_60",
            "question": "In the system commissioning process why is facility inspection important?",
            "options": [
                "The condition of the site and completed AV work can be inspected"
            ],
            "answer": "The condition of the site and completed AV work can be inspected"
        }
    ]
};
